name: trivy-fs

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '24 14 * * 5'

permissions:
  contents: read

jobs:
  scan-image:
    permissions:
      contents: read
      security-events: write
      actions: read
    name: scan-fs
    runs-on: "ubuntu-20.04"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          format: 'sarif'
          scan-type: 'fs'
          ignore-unfixed: true
          vuln-type: 'os,library'
          output: 'trivy-results.sarif'
          severity: 'MEDIUM,CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'

